### ISSUE TITLE
Tela de editar/criar Forms 

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/forms#1]
- [x] web: diminuindo a resolução abaixo de 990x o menu está ficando oculto.
![image](https://user-images.githubusercontent.com/29258164/138174511-7b16b379-e106-43a9-a5a7-a4672608cffd.png)

- [x] web: hoje ao criar ou editar um formulário, não existe botão de confirmar criação ou salvar edição. Se o usuário clica em criar e sai da página, automaticamente cria um formulário em branco, mesmo sem título. Seria interessante existir esses botões para confirmar o fluxo.
Atualização: Foi buscada uma forma mais simples de resolver o problema pois o formulário estava automatizado salvando as alterações à cada mudança no formulário, para não alterar toda essa estrutura foi criado um botão de exclusão na listagem, possibilitando essa limpeza dos formulários em branco.

- [x] mobile: alguns itens estão ficando em cima de outros. As frases precisam ser melhor alocadas. As caixas de texto e preview precisam ser fixadas lado a lado e o QR Code precisa ser responsivo de acordo com a resolução do mobile.
![image](https://user-images.githubusercontent.com/29258164/138160965-e09e694f-1d2c-4cbb-a776-b47d032bfdbf.png) ![image](https://user-images.githubusercontent.com/29258164/138160867-492075fa-ae3e-4db8-9642-f3a33e5587c7.png)

**Comment by CleissonVieira** [comment]
@zorteaadriano verifiquei que todos os itens estão marcados como concluídos
Existe algum pull request? Ainda está ajustando?

Lembrar de colocar Need Review quando concluído e realizar um Pull Request

**Comment by zorteaadriano** [comment]
![image](https://user-images.githubusercontent.com/74692811/154088587-b31a3e28-a8fb-4e99-a9a1-a18048493758.png)

Oi @CleissonVieira, hoje criei o pull request expliquei tudo o que foi alterado, mas aconteceu este erro, talvez tenha faltado incluir uns arquivos que pensei que não precisavam ser comitados, tipo esses aqui em baixo: 

![image](https://user-images.githubusercontent.com/74692811/154089125-4ef3698d-0edf-40cd-8563-69b459809b38.png)

Pensei que esses arquivos eram gerados automaticamente e não precisavam ser comitados, consegue dizer se foi isso mesmo que causou este erro?

**Comment by CleissonVieira** [comment]
Não estou vendo mensagem de erro na tela @zorteaadriano apenas informações de arquivos modificados. Talvez tem um print com mais detalhes?

**Comment by CleissonVieira** [comment]
Avisa aqui ou no Pull Request quando implementar a dica feita no PR e conversado em reunião

**Comment by alissonpeloso** [comment]
Oi, @zorteaadriano , como está a situação dessa issue?

**Comment by zorteaadriano** [comment]
Oi @alissonpeloso, então, na última reunião definimos com o Cleisson para inserir um botão de cancelar e tratar quando o usuário sair da tela para realizar a exclusão do formulário quando o mesmo estiver vazio. A parte de 'cancelar' está funcionando, porém ainda to com dificuldades pra pegar uma forma de excluir ao sair da tela, estou tentando ainda.
