### ISSUE TITLE
Divergência na contagem de respostas

### ISSUE THREAD

**Issue by zorteaadriano** [practice-uffs/forms#11]
Ao alterar uma pergunta em que já haviam respostas, as respostas da pergunta antiga não são mais listadas na aba de respostas, embora continuem contabilizando no total de respostas do formulário.

![image](https://user-images.githubusercontent.com/74692811/157763073-6fb5a846-894f-4f48-bc1b-6f48cb79241e.png)

Nesse exemplo alterei a pergunta para 'Minha nova pergunta', mas antes disso eu já havia respondido 3 vezes a pergunta antiga, e nesse caso a pergunta antiga não está mais sendo listada, embora esteja sendo contabilizada como resposta do formulário.

A proposta é alterar na listagem das perguntas para buscar todas as respostas buscando pelo id do formulário, tendo em vista 0,,que está buscando pelo texto da pergunta.

**Comment by alissonpeloso** [comment]
@zorteaadriano, não esquece de adicionar a issua pra sprint

**Comment by alissonpeloso** [comment]
@zorteaadriano, conseguiu resolver o esquema de usar a tag `old` nas respostas?

**Comment by zorteaadriano** [comment]
@alissonpeloso só estou ajustando ainda porque faltou listar as perguntas que não tem respostas ainda, como alterei pra ser ao contrário a listagem teria que manter essa função também, mas só vou conseguir fazer o commit hoje à noite, pois tenho aula hoje à tarde
