### ISSUE TITLE
Bug nas respostas únicas

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/forms#15]
Nas permissões tem a opção de deixar uma resposta única por pessoa (precisa logar no forms). No caso, se você realizar uma resposta e dar "ok" depois da confirmação, ele te redireciona pra mesma página de respostas. Isso faz com que você possa responder mais de uma vez. Acredito que se redirecionar para a página inicial depois de uma resposta nesse caso de configuração, ele funcione corretamente, pois se você fechar a aba e tentar entrar no link de resposta, ele não permite.

O objetivo desta issue é resolver esse problema e verificar se há mais casos como esse nas permissões das perguntas

**Comment by CleissonVieira** [comment]
Ao analisar está issue realizei testes em cima das permissões do forms.

Identifiquei que em produção:
- [ ] A opção "Aceitando respostas" não é funcional, pois, mesmo inativando, basta atualizar a página para o botão ficar ativo novamente. E sem atualizar a página ainda sim é possível enviar respostas.
- [ ] A opção de "Respostas únicas", comentada nesta issue, não funciona a necessidade de autenticação. Com essa opção ativa ainda consigo abrir o questionário em uma guia anonima e realizar respostas sem acessar uma conta.
- [ ] A opção de "Exigir autenticação para responder" não funciona. Com essa opção ativa ainda consigo abrir o questionário em uma guia anonima e realizar respostas sem acessar uma conta.

Em resumo as permissões não estão funcionando.
@alissonpeloso verifiquei que está issue está com status "Em progresso", existe alguém realizando a mesma?

**Comment by alissonpeloso** [comment]
Acredito que o Adriano iria trabalhar nela após ele conseguir fazer funcionar o websocket no forms para a atualização de respostas no livewire sem atualizar a página

**Comment by zorteaadriano** [comment]
@CleissonVieira, estive testando e reproduzindo essas situações que você descreveu e não consegui obter os mesmos problemas, verifiquei que as configurações estão funcionando, mesmo com o acesso em uma guia anônima. Mas também estive com problemas pra rodar tudo com as últimas alterações que o Alisson fez, eu precisei reinstalar o projeto todo do 0 para funcionar, aconselho fazer o mesmo e verificar se o websocket está funcionando corretamente (lembro que no meu navegador apareciam vários bloqueios do CORS que é feito pelo navegador, mas depois que o websocket passou a funcionar os erros pararam, então acredito que dá pra testar verificando isso também diretamente no console)

**Comment by CleissonVieira** [comment]
Conversei com @alissonpeloso, ele me informou que isso é devido a dependências desatualizados no meu ambiente de trabalho. Aconselhou remover o projeto e fazer um novo clone após atualizar as dependências.

Mas perfeito se essas situações não existem hehe

**Comment by alissonpeloso** [comment]
Como está a issue, @zorteaadriano ?

**Comment by zorteaadriano** [comment]
@alissonpeloso desculpa a demora pra responder, mas indo direto ao assunto tive problemas em exibir a mensagem de retorno quando a resposta era única, mesmo com o websocket funcionando a mensagem não aparecia e quando tentei arrumar parou de funcionar as respostas automáticas, mas depois consegui voltar ao estado normal e consegui exibir a mensagem de retorno, isso me atrasou um pouco. Portanto acabei fazendo da seguinte forma: o usuário é bloqueado ao tentar submeter uma segunda resposta em formulários de resposta única, a minha ideia era fazer o bloqueio após clicar 'ok' no balão de retorno, mas como ainda ficou complexo pra mim fazer esse controle na blade sucess do formulário, eu consegui passar mais informações do formulário e bloquear o usuário que tentar submeter uma segunda vez, acredito que não seja tão ruim pois assim ele ainda consegue ver as perguntas do formulário que respondeu, mas não pode submeter estando no mesmo usuário.
