### ISSUE TITLE
Tela de responder Formulários

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/forms#3]
Ao acessar um formulário e enviar sem preencher os campos é retornado um erro em código ```data.poll 0``` conforme imagem abaixo. É necessário traduzir o campo ao usuário
![image](https://user-images.githubusercontent.com/29258164/138176417-55116e5f-8c04-4eae-b2cf-710f16aa9215.png)

**Comment by alissonpeloso** [comment]
Oi, @zorteaadriano, como está a situação da issue?

**Comment by alissonpeloso** [comment]
@zorteaadriano, foi aberto PR dessa issue aqui?
 Acho que não foi dado merge na `dev`
