### ISSUE TITLE
Limpar código que não é utilizado no Forms e ajustar layout.

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/forms#8]
Muito código do forms foi reutilizado do mural, a intenção dessa issue é limpar o que não é utilizado dentro do Forms.

---

- [x] Também é necessário ajustar o footer no desktop e mobile:
![image](https://user-images.githubusercontent.com/51202705/157024023-31b6414c-8fcf-4253-a4d5-e1ad9ffcec15.png)
![image](https://user-images.githubusercontent.com/51202705/157024130-0847d0cb-45b0-4752-951f-ad1a51a1da74.png)

- [x] Assim como o header no modo mobile:
![image](https://user-images.githubusercontent.com/51202705/157024211-055b588e-f0be-48a2-8099-4ed272f77cd7.png)

**Comment by alissonpeloso** [comment]
Após realizar as alterações, atualizar a branch `dev` com as alterações do `main`

**Comment by alissonpeloso** [comment]
@zorteaadriano, lembra de adicionar em alguma sprint quando começar a executar

**Comment by zorteaadriano** [comment]
@alissonpeloso, ajustei o header e o footer, que era só remover os conteúdos do mural no rodapé e ajustar o menu pra alinhar os botões e a logo nas telas menores, resolvi esconder a imagem do perfil pra ter mais espaço nesse caso. Tive que adicionar um overflow-x: scroll na tabela de listagem dos formulários do usuário, pois a tabela não é responsiva e quebrava o o rodapé quando carregava naquela página, as vezes voltando pra uma versão maior de tela ele também quebrava. 

Era algo assim que esperava?

![image](https://user-images.githubusercontent.com/74692811/160550771-e5257129-fa32-4904-b28f-eb458c859f59.png)
![image](https://user-images.githubusercontent.com/74692811/160551510-d458b8a4-757c-45d5-a9fb-0cc187916c57.png)

**Comment by alissonpeloso** [comment]
Isso aí, ficou massa @zorteaadriano. Parabéns! 🎉

**Comment by zorteaadriano** [comment]
@alisson só ajustei ainda na versão menor, pois o nome exibindo quebrava o botão de abrir o menu, aí joguei lá dentro do dropdown
![image](https://user-images.githubusercontent.com/74692811/162103049-a7095841-eef6-401b-9909-ee42227081e7.png)

**Comment by alissonpeloso** [comment]
@zorteaadriano, lembra sempre de adicionar a tag "need review" na issue que precisa de revisão. Se possível, também vincula o PR nesta abinha da issue:
![image](https://user-images.githubusercontent.com/51202705/162435780-8aaf3bab-18eb-460d-a240-2e6b18333f21.png)

**Comment by zorteaadriano** [comment]
@alissonpeloso beleza, acabei só colocando o estado como 'aguardando algo', pensei que era suficiente
