### ISSUE TITLE
Corrigir problemas de UI/UX

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/forms#9]
## Desktop

- [x] Ajustar footer no modo
![image](https://user-images.githubusercontent.com/51202705/157232389-d75334f9-526c-4d5c-bc1e-a492a328f6fc.png)

- [x] Não aparece nada na página de respostas se não há respostas ainda (no momento de criação)
![image](https://user-images.githubusercontent.com/51202705/157232826-20cb0156-d2b8-4e9a-aec9-36068c586c1e.png)

- [x] Precisa adicionar wrap nos formulários criados
![image](https://user-images.githubusercontent.com/51202705/157233456-47edb5c7-a2a4-460b-a190-4323433a4f87.png)

- [x] Centralizar botão de Enviar na tela "Responder" 
![image](https://user-images.githubusercontent.com/51202705/157235966-c10818b0-0a59-4e9e-a84c-fb76aafc1fda.png)

---

## Mobile

- [x] Ajustar o header
![image](https://user-images.githubusercontent.com/51202705/157234130-df83c052-0fa0-431c-8f17-6b14442f9eaa.png)

- [x] Diminuir espaçamento, página inicial
![image](https://user-images.githubusercontent.com/51202705/157234456-68b2fbc9-8b93-4044-9c9b-74000d14f16e.png)

- [x] Ajustar padding, página inicial
![image](https://user-images.githubusercontent.com/51202705/157234641-5407b1c9-f173-4407-be09-adbe56b0b97b.png)

- [x] Ajustar o exemplo, acho que dá pra colocar um abaixo do outro
![image](https://user-images.githubusercontent.com/51202705/157234760-fd4ed2da-605b-4037-9d12-836356c0981b.png)

- [x] Centralizar a animação de gráficos
![image](https://user-images.githubusercontent.com/51202705/157234908-89021718-3b1e-4aba-9d21-8b255952445c.png)

- [x] Ajustar footer
![image](https://user-images.githubusercontent.com/51202705/157235044-c132abfd-41f4-4aa9-86b9-282ae9e5eecf.png)

- [x] Overflow nos forms criados (talvez um overflow-x com scroll resolva)
![image](https://user-images.githubusercontent.com/51202705/157235338-5facf09a-6416-4018-a880-4b84056e27b2.png)

- [x] Corte na visualização do form, talvez um padding-bottom
![image](https://user-images.githubusercontent.com/51202705/157235803-133d8efe-a43a-44a1-a843-15d83bc5e959.png)

- [x] Centralizar botão de "enviar" na tela "responder"
![image](https://user-images.githubusercontent.com/51202705/157236194-9696b743-7d63-40a4-b6e2-c5f13d781b6a.png)

**Comment by zorteaadriano** [comment]
@alissonpeloso vou fazer separando por commit, acho que fica ok dessa forma

**Comment by alissonpeloso** [comment]
Você que sabe, se quiser, pode dividir cada checkbox em uma issue também
